# NUMPY: Numerical python
         MOST COMMONLY USED PYTHON LIBRARY FOR DATA SCIENCE.THIS LIBRARY IS WRRITEN FOR SCIENTIFIC COMPUTING AND DATA 
         ANALYSIS.BASIC NUMPY OBJECT IS "NDARRAY(N-DIMENSIONAL ARRAY)".THIS IS HOMOGENEOUS ARRAY MEANZ ALL THE DATA IN
         THIS ARRAY IS OF SAME DATA TYPE.USUALLY IN NUMPY ARRAY WE USE EITHER FLOAT OR INTEGER DATA TYPE.

## why NUMPY?
      IT IS VERY FAST AND SECOND ONE IS ITS COMPUTING.IT IS VERY CONVIENIENT TO USE.
      IMPLEMENTATION OF NUMPY IS COMPLETELY IN C PROGRAMMING SO AT THE BACKEND EVERYTHING RUNS IN THE C PROGRAMMING.
      IT AVOID ALL THE GENERAL LOOP IN PYTHON AND IN DIRECTIONSAND ALSO AVOID DYNAMIC TYPECHECKING.
      NUMPY USE THE CONCEPT OF PARELELISM ON THE OTHER HAND LIST WORKS SEQUENTIALY SO NUMPY IS FAR BETTER THEN SIMPLE PYTHON
      LIST.

### numpy use less storage save space

In [1]:
import numpy
r=numpy.array([1,2,3,4,5])
r

array([1, 2, 3, 4, 5])

In [2]:
r[[2,3,4]]

array([3, 4, 5])

In [3]:
import numpy as np      ## here np is the alias or shortcut for numpy

In [4]:
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a.shape

(9,)

In [6]:
a.dtype

dtype('int32')

In [7]:
a.ndim

1

In [8]:
a>3

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [9]:
a>2

array([False, False,  True,  True,  True,  True,  True,  True,  True])

In [10]:
d=np.arange(100)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
c=range(100)
c

range(0, 100)

In [12]:
timeit(i**2 for i in range c)

SyntaxError: invalid syntax (<unknown>, line 1)

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.eye((10))                        ## identity matrix 

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
np.full((4,4),4)                    ## row and column exactly have the same value

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [17]:
np.full((3,4),5.5)

array([[5.5, 5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5, 5.5]])

In [18]:
np.full((3,4),5.5 , dtype=np.int)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [19]:
np.diag((1,2,3,4))     

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [20]:
z=np.array([1,2,3,4])
z

array([1, 2, 3, 4])

In [21]:
np.tile(z,(3,1))

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [22]:
np.random.random()

0.5413125278856544

In [23]:
20*np.random.random()+2

5.529450793271769

In [24]:
np.random.random([6,3])

array([[0.66574902, 0.87382815, 0.04625117],
       [0.8620864 , 0.07844262, 0.77757377],
       [0.9073274 , 0.0349247 , 0.54348953],
       [0.67386579, 0.37199112, 0.82148786],
       [0.44493068, 0.57846832, 0.60859162],
       [0.03682779, 0.7030364 , 0.48158341]])

In [25]:
a=np.linspace(1,20,100)            ## this function divide 1 to 20 values into 100 times means 100 time divisinons
a

array([ 1.        ,  1.19191919,  1.38383838,  1.57575758,  1.76767677,
        1.95959596,  2.15151515,  2.34343434,  2.53535354,  2.72727273,
        2.91919192,  3.11111111,  3.3030303 ,  3.49494949,  3.68686869,
        3.87878788,  4.07070707,  4.26262626,  4.45454545,  4.64646465,
        4.83838384,  5.03030303,  5.22222222,  5.41414141,  5.60606061,
        5.7979798 ,  5.98989899,  6.18181818,  6.37373737,  6.56565657,
        6.75757576,  6.94949495,  7.14141414,  7.33333333,  7.52525253,
        7.71717172,  7.90909091,  8.1010101 ,  8.29292929,  8.48484848,
        8.67676768,  8.86868687,  9.06060606,  9.25252525,  9.44444444,
        9.63636364,  9.82828283, 10.02020202, 10.21212121, 10.4040404 ,
       10.5959596 , 10.78787879, 10.97979798, 11.17171717, 11.36363636,
       11.55555556, 11.74747475, 11.93939394, 12.13131313, 12.32323232,
       12.51515152, 12.70707071, 12.8989899 , 13.09090909, 13.28282828,
       13.47474747, 13.66666667, 13.85858586, 14.05050505, 14.24

In [26]:
a.itemsize

8

In [27]:

b=np.arange(18)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [28]:
b.shape

(18,)

In [29]:
c=b.reshape(3,2,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [30]:
c.shape

(3, 2, 3)

In [31]:
c=b.reshape(3,2,-1)                 ## here -1 automatically adjust the dimension 
c

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [32]:
h=np.arange(10)
h

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
l=h

In [34]:
l

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
l[2]=89

In [36]:
l

array([ 0,  1, 89,  3,  4,  5,  6,  7,  8,  9])

In [37]:
h

array([ 0,  1, 89,  3,  4,  5,  6,  7,  8,  9])

In [38]:
np.shares_memory(h,l)

True

In [39]:
e=np.arange(10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
y=e.copy()                  ## not impact on each other

In [41]:
print(y)

[0 1 2 3 4 5 6 7 8 9]


In [42]:
y[3]=14
y

array([ 0,  1,  2, 14,  4,  5,  6,  7,  8,  9])

In [43]:
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.shares_memory(e,y)

False

In [45]:
a=np.array([[3,4,5,6],[2,9,10,4],[3,4,5,6]])
a

array([[ 3,  4,  5,  6],
       [ 2,  9, 10,  4],
       [ 3,  4,  5,  6]])

In [46]:
a.T

array([[ 3,  2,  3],
       [ 4,  9,  4],
       [ 5, 10,  5],
       [ 6,  4,  6]])

In [47]:
b=np.array([[3,4,7,10],[67,89,56,48],[2,5,7,8]])
b

array([[ 3,  4,  7, 10],
       [67, 89, 56, 48],
       [ 2,  5,  7,  8]])

In [48]:
a == b

array([[ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [49]:
np.vstack((a,b))                              ## vertical stack

array([[ 3,  4,  5,  6],
       [ 2,  9, 10,  4],
       [ 3,  4,  5,  6],
       [ 3,  4,  7, 10],
       [67, 89, 56, 48],
       [ 2,  5,  7,  8]])

In [50]:
np.hstack((a,b))                             ## horizontal stack

array([[ 3,  4,  5,  6,  3,  4,  7, 10],
       [ 2,  9, 10,  4, 67, 89, 56, 48],
       [ 3,  4,  5,  6,  2,  5,  7,  8]])

In [51]:
np.sin(a)

array([[ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.90929743,  0.41211849, -0.54402111, -0.7568025 ],
       [ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ]])

In [52]:
np.cos(b)

array([[-0.9899925 , -0.65364362,  0.75390225, -0.83907153],
       [-0.5177698 ,  0.51017704,  0.85322011, -0.64014434],
       [-0.41614684,  0.28366219,  0.75390225, -0.14550003]])

In [53]:
np.tan(a)

array([[-0.14254654,  1.15782128, -3.38051501, -0.29100619],
       [-2.18503986, -0.45231566,  0.64836083,  1.15782128],
       [-0.14254654,  1.15782128, -3.38051501, -0.29100619]])

In [54]:
np.exp(a)

array([[2.00855369e+01, 5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [7.38905610e+00, 8.10308393e+03, 2.20264658e+04, 5.45981500e+01],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02, 4.03428793e+02]])

In [55]:
np.median(a)

4.5

In [56]:
np.sum(a)

61

In [57]:
np.std(a)

2.289771944005681

In [6]:
k=np.arange(10).reshape(2,-1)
k

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
import numpy as np

In [8]:
from numpy import linalg as LA

In [9]:
np.linalg.det(k)


LinAlgError: Last 2 dimensions of the array must be square

In [10]:
np.linalg.inv(k)

LinAlgError: Last 2 dimensions of the array must be square

In [60]:
a=np.array([1,1,0],dtype=bool)
b=np.array([1,0,0],dtype=bool)


In [61]:
np.logical_or(a,b)

array([ True,  True, False])

In [62]:
np.logical_and(a,b)

array([ True, False, False])

In [63]:
np.logical_not(a,b)

array([False, False,  True])

In [64]:
np.all(a==a)

True

In [65]:
a=np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7]])
a

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [66]:
np.sum(a)

46

In [67]:
a.sum(axis=0)                       ## add coloumn wise

array([ 7, 10, 13, 16])

In [68]:
a.sum(axis=1)                         ## add row wise

array([10, 14, 22])

In [69]:
a.max

<function ndarray.max>

In [70]:
a.max()

7

In [73]:
a.argmax()                 ## index position

11

In [72]:
a

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [74]:
a=np.arange(1,10)

In [75]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
a[:,np.newaxis].shape            ## convertin 1-d array into 2-d array

(9, 1)